name = "castlecrewweb"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
account_id = "887592f075b0c3940eb9f2fd353fcdd9"

[[d1_databases]]
binding = "DB"
database_name = "castle-db"
database_id = "14c3aebd-86c7-4529-aba0-bb6ddf0b9e7f"

[vars]
# Secrets are managed in Cloudflare Dashboard or .dev.vars for local dev
GOOGLE_WALLET_ISSUER_ID = "3388000000023062718"
# GOOGLE_WALLET_CREDENTIALS = "" # Set this in Cloudflare Pages Settings -> Environment Variables

